filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /cowrie/cowrie-git/var/log/cowrie/cowrie.json
    json.keys_under_root: true
    json.add_error_key: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
