filebeat.inputs:
  - type: log
    paths:
      - /cowrie/cowrie-git/var/log/cowrie/cowrie.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # Uncomment if authentication is required
  # username: "elastic"
  # password: "yourpassword"

setup.template.name: "cowrie"
setup.template.pattern: "cowrie-*"
output.elasticsearch.index: "cowrie-%{+yyyy.MM.dd}"
